"""Add person_count to bookings

Revision ID: 273f9a97afa8
Revises: d55774462078
Create Date: 2024-10-17 16:35:46.813164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '273f9a97afa8'
down_revision = 'd55774462078'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('bookings', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('person_count', sa.Integer(), nullable=False))
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('bookings', schema=None) as batch_op:
        # batch_op.drop_column('person_count')
    pass
    # ### end Alembic commands ###
