"""Added person_count to Booking model

Revision ID: 3303f6593f54
Revises: fc4c8c0521d4
Create Date: 2024-10-18 10:26:17.363035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3303f6593f54'
down_revision = 'fc4c8c0521d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('person_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('person_count')

    # ### end Alembic commands ###
